/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router and will be overwritten.
import { Route as rootRouteImport } from "./routes/__root";
import { Route as ApiHealthRouteImport } from "./routes/api.health";
import { Route as ApiV1MeRouteImport } from "./routes/api.v1.me";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as IndexRouteImport } from "./routes/index";

const ApiHealthRoute = ApiHealthRouteImport.update({
  id: "/api/health",
  path: "/api/health",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: "/api/v1/me",
  path: "/api/v1/me",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export const routeTree = rootRouteImport._addFileChildren({
  ApiHealthRoute,
  ApiV1MeRoute,
  DashboardRoute,
  IndexRoute,
});

